### ISSUE TITLE
No Module named pyinsane2 

### ISSUE THREAD

**Issue by Maier123** [openpaperwork/pyinsane#41]
Hello, 
when running any of the files of this rep, after I have succssefully build and installed the[ setup.py ](url)file, it gives me ModuleNotFoundError: NO module named 'pyinsane2'. 
Has anyone experienced this before or can help me with fixing this ? 
The module is listed under installed modules and it is added to my SYS.PATH.

**Comment by jflesch** [comment]
1) Which OS are you using ?
2) What commands did you use exactly to install Pyinsane ?

**Comment by Maier123** [comment]
Im using Python3.6 on Windows 8. 
First I typed setup.py build then I installed it with setup.py install.

**Comment by jflesch** [comment]
[Building Pyinsane2 on Windows is actually quite complex and require many tools](https://github.com/openpaperwork/pyinsane/#note-regarding-the-wia-2-implementation). I haven't even tested it recently with anything more recent than Python 3.4.
Are you sure both commands were successful ? (no error message at all ?)

Do you use Msys2, Cygwin, or Python + Visual C++ ?

**Comment by Maier123** [comment]
Okay so I removed the whole pyinsane2 folder and reinstalled it, now running python setup.py install gives me an ImportError: cannot import name "version"
sorry for all the questions

**Comment by jflesch** [comment]
> ImportError: cannot import name "version"

Yep sorry, I'm working on the build system.
So either you have the command 'make' available, in which case you can simply run 'make install' instead of 'python ./setup.py install' or I suggest you switch back to the latest stable / tagged version --> `git checkout 2.0.10`

**Comment by Maier123** [comment]
Where can I find git checkout 2.0.10?

**Comment by jflesch** [comment]
It's a command. You're supposed to type it In a terminal. For instance in CMD.EXE if Git is in your PATH.

**Comment by Maier123** [comment]
So I should try to get the latest Python 3.4 version ? And how to I add Git to my path? Import sys and then sys.path.append(git) ? Thanks for all your help!

**Comment by jflesch** [comment]
Git is a version control software. It is the one used everywhere on Github. https://try.github.io/
2.0.10 is the latest version of Pyinsane tagged in Pyinsane's repository.

You must have a the correct version of Visual C++ (with C headers) in order to have a vague chance of building Pyinsane. The version of Visual C++ you install must match your version of Python  : https://wiki.python.org/moin/WindowsCompilers

Windows DDK: https://www.microsoft.com/en-us/download/details.aspx?id=11800

Again, I've tested Pyinsane only with Python 3.4 + Visual C++ 2010. I cannot guarantee it will even compile with anything else.

**Comment by Maier123** [comment]
I solved the problem by simply using python scan.py in my cmd.exe!
